### ISSUE TITLE
Sintesis_corregido 

### ISSUE THREAD

**Issue by AmilkarVladimiR** [SistemasTecTlaxiaco/actividad-3-sintesis-AmilkarVladimiR#3]
[sintesis_Corregido .pdf](https://github.com/user-attachments/files/16839785/sintesis_Corregido.pdf)

**Comment by saul19bautista** [comment]
ENTENDIBLE Y BIEN DESARROLLADO 
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
